# -*- coding: utf-8 -*-
"""Yeddu_Nikhil_Bhushan_Pandas_Customer Orders Inspection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-JGl34__GNYZOJ9gN3u0MhDtirwODXm
"""

import pandas as pd
df=pd.read_csv("/content/orders.csv",index_col="order_id")
print(df.head(5))

df.info()

"""1.20 rows and 6 columns.


2.quantity - 4 missing valus.
  order_date- 4 missing values.


3.order_date need data type conversion . pd.to_datetime() function is used for conversion.


"""

df.describe()

"""1.Median is the 50th percentile value : 2500


2.Yes the unit_price are appeared to be skewed. Beacause the mean=20224 and median=2500 as mean>median indicates right skew.
A few high prices pull the average upward.
"""